#!/bin/sh
# Copyright (C) 2014 Alexander Keller <github@nycroth.com>
# Copyright (C) 2019 Stephen Gregoratto <dev@sgregoratto.me>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
export INTERFACE="${INTERFACE:-wlan0}"

# die if the interface isn't wireless.
[ ! -d "/sys/class/net/$INTERFACE/wireless" ] && exit

# If the interface exists but no connection is active, display "down" in red.
if read -r state < "/sys/class/net/$INTERFACE/operstate" &&
	[ "$state" = "down" ]; then
	cat <<-EOF
	down
	down
	#FF0000
	EOF
	exit
fi

awk '
$1 ~ ENVIRON["INTERFACE"]{quality = int($3 * 100 / 70); nextfile}
END{
	print quality"%"
	print quality"%"
	if (quality >= 80)
		print "#00FF00"
	else if (quality >= 60)
		print "#FFF600"
	else if (quality >= 40)
		print "#FFAE00"
	else
		print "#FF0000"
}' /proc/net/wireless
