#! /bin/sh

blockdate=$(date '+%a. %d. %b. %Y')

case "$BLOCK_BUTTON" in
    1|2|3) date=$(date '+%A, %d. %B')
export TERM=xterm

#resize the date when it's longer than 22 chars
datelen=$(echo $date | wc -m )
if [ $datelen -gt 22 ]; then
    date=$(date '+%A %d. %b.')
fi
# use sed to translate highlighted day to pango syntax
cal --color=always \
    | sed 's/\x1b\[[7;]*m/\<b\>\<u\>/g' \
    | sed 's/\x1b\[[27;]*m/\<\/u\>\<\/b\>/g' \
    | tail -n +2 \
    | sed 's/^/ /' \
    | rofi \
        -dmenu \
        -markup-rows \
        -no-fullscreen \
        -font "Monospace 6" \
        -hide-scrollbar \
        -bw 2 \
        -m -3 \
        -theme-str '#window {anchor:southeast; location: northwest;}' \
        -eh 1 \
        -width -22 \
        -no-custom \
        -p "$date" > /dev/null 
    esac
echo $blockdate
date '+%d.%m.%Y'
