#! /bin/sh

width=200
height=200
datefmt="+%a %d.%m.%Y %H:%M:%S"

case "$BLOCK_BUTTON" in
  1|2|3) 

	# the position of the upper left corner of the popup
	posX=$(($BLOCK_X - $width / 2))
	posY=$(($BLOCK_Y - $height))

	i3-msg -q "exec yad --calendar \
        --width=$width --height=$height \
	    --undecorated --fixed \
	    --close-on-unfocus --no-buttons \
	    --posx=$posX --posy=$posY \
	    > /dev/null"
esac
date "$datefmt"
