#!/bin/bash
#UPDATES=$(checkupdates)
UPDATECOUNT=$( checkupdates | wc -l)
#load colors from wal
. /home/omicron/.cache/wal/colors.sh

markup(){
    red="#ff0000"
    green="#00ff00"
    white="${foreground}"
    close="</span>"
    #make an array of checkupdates output lines
    mapfile -t updates < <(checkupdates)

    for line in "${updates[@]}";
        do 
         
        echo "$line" | awk -F " " '{ print $1 "<span color=\"'$red'\"> "$2"'$close'<span color=\"'$white'\"> "$3"'$close'<span color=\"'$green'\"> "$4"'$close'" }'
        done
}


show_updates(){
if [ "$UPDATECOUNT" == 0 ] ; then 
    echo "0"
    exit 0
    pkill -RTMIN+3 i3blocks
elif
    [ "$UPDATECOUNT" -gt 20 ] ; then
    line_num=20
else
    line_num="$UPDATECOUNT"
fi
    markup \
        | sed 's/^/ /' \
        | rofi -no-fullscreen -width -50 -bw 2 -m -3 -theme-str '#window {anchor:southeast;}' -eh 1 -font 'Monospace 6' -dmenu -p "Available updates" -markup-rows -lines "${line_num}"  > /dev/null
    echo "$UPDATECOUNT"
    echo "$UPDATECOUNT"
    pkill -RTMIN+3 i3blocks
    exit 0

}

case $TEST in
    1) markup
        ;;
esac

case $BLOCK_BUTTON in
    3) gksu -k 'xfce4-terminal -x aura -Syu --noconfirm'
        exit 0
        ;;
    1|2) show_updates
        exit 0
        ;;
esac
    echo "$UPDATECOUNT"
    echo "$UPDATECOUNT"

