#!/bin/bash

[[ -n $BLOCK_INSTANCE ]] || BLOCK_INSTANCE=wlan0

dbm=$(iw dev $BLOCK_INSTANCE link | grep -Eoe '-[0-9]{2}')

[[ -n $dbm ]] || exit 0

echo ${dbm} dBm
echo ${dbm} dBm

if [[ $dbm -ge -55 ]]; then
	echo \#00FF00
elif [[ $dbm -ge -60 ]]; then
	echo \#CCFF00
elif [[ $dbm -ge -70 ]]; then
	echo \#FFFF00
elif [[ $dbm -ge -80 ]]; then
	echo \#FFAA00
else
	echo \#FF0000
fi
