#!/usr/bin/env bash

[[ -x "$(command -v powerprofilesctl)" ]] || exit

print_block() {

   current="$(powerprofilesctl get)"
   echo "${current}"

}

profile_switch() {
   IFS=$'\n'
   current="$(powerprofilesctl get)"
   profiles=( $(gdbus introspect --system --dest net.hadess.PowerProfiles --object-path /net/hadess/PowerProfiles --only-properties |sed -n "s/.*Profiles = //;s/\;//;s/'/\"/g;s/<//g;s/>//gp"|jq --raw-output '.[].Profile') )
   currentIndex="$(for i in "${!profiles[@]}"; do [[ "${profiles[$i]}" = "${current}" ]] && echo "${i}" && break; done)"
   totalProfiles="${#profiles[@]}"

   (( nextProfile = $currentIndex $1 ))
   if (( $nextProfile >= $totalProfiles )); then nextProfile="0"; fi
   powerprofilesctl set "${profiles[$nextProfile]}" 
   pkill "-RTMIN+${signal}" i3blocks

}

case "${BLOCK_BUTTON}" in
	1) profile_switch "+1" ;;
	3) profile_switch "-1" ;;
esac

print_block
