#!/usr/bin/env sh
# Copyright (C) 2021 Marcos Felipe Eipper <marcos@eipper.com.br>

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

CURRENT_GPU=$(optimus-manager --status | awk '/Current/ {print $5}')

case $BLOCK_BUTTON in
    1) optimus-manager --switch $(if [ "${CURRENT_GPU}" = "intel" ]; then echo "nvidia"; else echo "intel"; fi) --no-confirm ;;
esac

echo "${CURRENT_GPU}"
