#!/bin/sh

# Copyright (C) 2018 Nikolas De Giorgis <nikolas.degiorgis@gmail.com>

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

IFS=
result=`speedtest-cli --bytes --simple`
PING=`echo $result | sed -n 1p |cut -d ':' -f2 | cut -d ' ' -f2`

DOWN=`echo $result | sed -n 2p |cut -d ':' -f2 | cut -d ' ' -f2`

UP=`echo $result | sed -n 3p |cut -d ':' -f2 | cut -d ' ' -f2`

echo  $PING" ms" $DOWN "MB/s" $UP "MB/s"
