#!/usr/bin/bash
# Copyright (C) 2014 Tony Crisci <tony@dubstepdish.com>
# Copyright (C) 2015 Thiago Perrotta <perrotta dot thiago at poli dot ufrj dot br>
# Copyright (C) 2023 Gesh <gesh@gesh.uni.cx>

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

# For all media players, MPRIS support should be enabled and the playerctl
# binary should be in your path.
# See https://github.com/acrisci/playerctl

# Set instance=NAME in the i3blocks configuration to specify a music player
# (playerctl will attempt to connect to org.mpris.MediaPlayer2.[NAME] on your
# DBus session). If instance is empty, playerctl will connect to the first
# supported media player it finds.

playerctl() {
    command playerctl ${BLOCK_INSTANCE+"--player=$BLOCK_INSTANCE"} "$@" \
        </dev/null
}

getMetadata() {
    playerctl metadata -F \
        --format $'{{default(artist, "\004\005")}} - {{title}}' \
        | sed -u $'s/^\004\005 - //;s/^[[:space:]]*//;s/[[:space:]]*$//'
}

case "$BLOCK_INSTANCE" in
    spotify)
        # Delay to let network-based players (spotify) reflect new data.
        networkDelay() {
            delay=50 # in ms
            : "${delayus:=$(bc <<<"$delay * 0.001")}"
            sleep "$delayus"
        }
    ;;
    *) networkDelay() { :; } ;;
esac

getMetadata &

while read -r button; do
    case "$button" in
        1) playerctl previous && networkDelay ;;
        2) playerctl play-pause ;;
        3) playerctl next && networkDelay ;;
        4) playerctl volume 0.01+ ;;
        5) playerctl volume 0.01- ;;
    esac
done
