#!/usr/bin/env bash
# Author: zDEFz

OPTIONS="Options:
    -class       --classname               Get classname of current window
    -title       --titlename               Get titlename of current window
    -dim         --dimensions              Get window dimensions of current window
    -pos         --position                Get window positions of current window
"

function print_usage() {
  printf "Usage:\n"
  printf "\n$(basename "$0") %s\n\n" "$OPTIONS"
}

function getClassname()
{
    classname="$(xdotool getactivewindow getwindowclassname)"
    echo "class=[$classname]"
}

function getTitlename()
{
    #get titlename
    titlename="$(xdotool getactivewindow getwindowname)"
    echo "title=[$titlename]"
}

function getWindowDimensions()
{
    windowdimensions="$(xdotool getactivewindow getwindowgeometry | grep Geometry | cut -d ':' -f2)"
    echo "Dim:$windowdimensions"
}

function getWindowPosition()
{
    windowposition="$(xdotool getwindowgeometry $(xdotool getactivewindow) | grep "Position" | awk '{print $2}')"
    echo "Pos:$windowposition"
}

while true; do
  if [ -z "$1" ]; then
    print_usage
    exit 1
  fi
  case "$1" in
  -class | --classname)
    getClassname
    exit 1
    ;;
  -title | --titlename)
    getTitlename
    exit 0
    ;;
  -dim | --dimensions)
    getWindowDimensions
    exit 0
    ;;
  -pos | --position)
    getWindowPosition
    exit 0
    ;;
  esac; done
