#!/bin/bash
#
# Copyright (C) 2015 James Murphy                                                  
# Licensed under the terms of the GNU GPL v2 only.                                 
#                                                                                  
# i3blocks blocklet script to display pending system upgrades 

# FontAwesome refresh symbol, change if you do not want to install FontAwesome
REFRESH_SYMBOL="\uf021 "

# By default, show both the symbol and the numbers
SYMBOL_ONLY=0

# By default, show something when no upgrades are pending
ALWAYS_PRINT=1

# Colors for when there is/isn't a pending upgrade
REFRESH_COLOR="#00FF00"
NONREFRESH_COLOR="#FFFFFF"

while getopts s:oc:n:Nh opt; do
    case "$opt" in
        s) REFRESH_SYMBOL="$OPTARG" ;;
        o) SYMBOL_ONLY=1 ;;
        c) REFRESH_COLOR="$OPTARG" ;;
        N) ALWAYS_PRINT=0 ;;
        n) NONREFRESH_COLOR="$OPTARG" ;;
        h) printf "Usage: apt-upgrades [-s refresh_symbol] [-o] [-c refresh_color] [-N|-n nonrefresh_color] [-h]\nOptions:\n-s\tSpecify a refresh symbol\n-o\tShow refresh symbol only, but no numbers\n-c\tColor when upgrade is pending\n-n\tColor when no upgrade is pending\n-N\tOnly display text if upgrade is pending (supercedes -n)\n-h\tShow this help text\n" && exit 0;;
    esac
done

read upgraded new removed held < <(
aptitude full-upgrade --simulate --assume-yes |\
    grep -m1 '^[0-9]\+ packages upgraded,' |\
    tr -cd '0-9 ' |\
    tr ' ' '\n' |\
    grep '[0-9]\+' |\
    xargs echo)

if [ $upgraded -ne 0 ] || [ $new -ne 0 ] || [ $removed -ne 0 ] || [ $held -ne 0 ]; then
    color="$REFRESH_COLOR"
    if [ $SYMBOL_ONLY -eq 1 ]; then
        echo -e "$REFRESH_SYMBOL"
        echo -e "$REFRESH_SYMBOL"
    else
        echo -e "$REFRESH_SYMBOL$upgraded/$new/$removed/$held"
        echo -e "$REFRESH_SYMBOL$upgraded/$new/$removed/$held"
    fi
    echo $color
elif [ $ALWAYS_PRINT -eq 1 ]; then
    color="$NONREFRESH_COLOR"
    echo -e "$REFRESH_SYMBOL$upgraded/$new/$removed/$held"
    echo -e "$REFRESH_SYMBOL$upgraded/$new/$removed/$held"
    echo $color
fi

