#!/bin/bash
#
# Copyright (C) 2015 James Murphy                                                  
# Licensed under the terms of the GNU GPL v2 only.                                 
#                                                                                  
# i3blocks blocklet script to display pending system upgrades 

# FontAwesome refresh symbol, change if you do not want to install FontAwesome
REFRESH_SYMBOL="\uf021 "

# By default, show both the symbol and the numbers
SYMBOL_ONLY=0

# Colors for when there is/isn't a pending upgrade
REFRESH_COLOR="#00FF00"
NONREFRESH_COLOR="#FFFFFF"

while getopts s:oc:n:h opt; do
    case "$opt" in
        s) REFRESH_SYMBOL="$OPTARG" ;;
        o) SYMBOL_ONLY=1 ;;
        c) REFRESH_COLOR="$OPTARG" ;;
        n) NONREFRESH_COLOR="$OPTARG" ;;
        h) printf "Usage: apt-upgrades [-s refresh_symbol] [-o] [-c refresh_color] [-n nonrefresh_color] [-h]\nOptions:\n-s\trefresh symbol\n-o\tshow symbol only, no numbers\n-c\tcolor when upgrade pending\n-n\tcolor when no upgrade pending\n-h\tshow this help text\n" && exit 0;;
    esac
done

read upgraded new removed held < <(
aptitude full-upgrade --simulate --assume-yes |\
    grep -m1 '^[0-9]\+ packages upgraded,' |\
    tr -cd '0-9 ' |\
    tr ' ' '\n' |\
    grep '[0-9]\+' |\
    xargs echo)

if [ $upgraded -ne 0 ] || [ $new -ne 0 ] || [ $removed -ne 0 ] || [ $held -ne 0 ]; then
    color="$REFRESH_COLOR"
    if [ $SYMBOL_ONLY -eq 1 ]; then
        echo -e "$REFRESH_SYMBOL"
        echo -e "$REFRESH_SYMBOL"
        echo $color
        exit 0
    fi
else
    color="$NONREFRESH_COLOR"
fi

echo -e "$REFRESH_SYMBOL$upgraded/$new/$removed/$held"
echo -e "$REFRESH_SYMBOL$upgraded/$new/$removed/$held"
echo $color
