#! /usr/bin/perl
sub print_average
{
    $temp_total = $_[0];
    $temp_count = $_[1];
    $decimals = $_[2];
    
    my $length = 4 + $decimals;

    printf "%${length}.${decimals}fC\n", $temp_total / $temp_count;
}

use strict;
use warnings;
use utf8;
use Getopt::Long;

# default values
my $short_label = $ENV{SHORT_LABEL} // "";
my $decimals = $ENV{DECIMALS} // 1;
my $use_average = $ENV{USEAVERAGE} // 0;

#
my $any_high_temp = 0;
my $any_crit_temp = 0;
my @all_temps = ();
my $temp_count = 0;
my $temp_total = 0;
my $is_in_coretemp = 0;
my $full_text = "";

open (TEMP, 'sensors |') or die;
while (<TEMP>) {
    if(/coretemp/){
        $is_in_coretemp = 1;
    } elsif(/^$/){
        $is_in_coretemp = 0;
    }
    if($is_in_coretemp){
        if (/^.*°C.*$/){
            my $tmp_string = $&;
            my $temp = "0";
            if($tmp_string =~ /\d*\.\d*/){
                $temp = $&;
            }
            
            my $high_temp = "";
            if($tmp_string =~ /(?<=high\ =\ [+-])\d*.\d*/){
                $high_temp = $&;
            }

            my $crit_temp = "";
            if($tmp_string =~ /(?<=crit\ =\ [+-])\d*.\d*/){
                $crit_temp = $&;
            }

            if($crit_temp && $temp >= $crit_temp){
                $any_crit_temp = 1;
                $full_text = "${full_text}<span color='red'>(${temp}C)</span>";
            } elsif ($high_temp && $temp >= $high_temp) {
                $any_high_temp = 1;
                $full_text = "${full_text}<span color='yellow'>(${temp}C)</span>";
            } else {
                $full_text = "${full_text}(${temp}C)";
            }
            $temp_count += 1;
            $temp_total = $temp_total + $temp;
        }
    }
}
close(TEMP);

# Print full_text
if($use_average){
    print_average($temp_total, $temp_count, $decimals);
} else {
    print $full_text, "\n";
}

# Print short_text
print $short_label;
print_average($temp_total, $temp_count, $decimals);

# Print colors if needed
if($any_crit_temp){
    print "#FF0000\n";
} elsif ($any_high_temp){
    print "#FFFC00\n";
}

exit 0;