#!/bin/bash
# Licensed under the terms of the GNU GENERAL PUBLIC LICENSE v2, or any later version.

#
# date pattern, more at 'man date'
#

DATE_PATTERN="%H:%M:%S %d.%m.%Y"

#
# command after clicking
#

CAL="gsimplecal"

#---------------------------------------------------------------

if [ "${BLOCK_BUTTON}" == "1" ]; then 
	$CAL
fi

date +"$DATE_PATTERN"                                  
